In [9]:
# import libraries
import pandas as pd
import numpy as np
from sklearn.metrics import mean_squared_error

In [2]:
# import feature data
data = pd.read_csv('../data/processed_data/Wildfire_Weather_2020_2024.csv')

In [3]:
# view feature data
data.head()

,unique_id,size (km2),perimiter (km),startdate,enddate,duration,fire_line (km),fire_spread (km2/day),fire_speed (km/day),dominant_direction,...,d2m,t2m,msl,sp,lai_hv,lai_lv,tp,ssr,datetime,dist
0,2020_22784,4.93,11.11,2020-01-06 00:00:00,2020-01-13 00:00:00,8,1.1,0.62,0.88,southeast,...,278.64328,284.38715,102901.520,102447.460,2.988195,2.407728,0.000021,8017088.0,2020-01-09,6565.323606
1,2020_22784,4.93,11.11,2020-01-06 00:00:00,2020-01-13 00:00:00,8,1.1,0.62,0.88,southeast,...,287.59494,292.01648,102516.750,102070.190,2.986613,2.406662,0.000020,5444096.0,2020-01-10,6565.323606
2,2020_22784,4.93,11.11,2020-01-06 00:00:00,2020-01-13 00:00:00,8,1.1,0.62,0.88,southeast,...,287.74893,289.71127,102244.630,101797.350,2.983510,2.404584,0.003486,8655968.0,2020-01-12,6565.323606
3,2020_22784,4.93,11.11,2020-01-06 00:00:00,2020-01-13 00:00:00,8,1.1,0.62,0.88,southeast,...,278.82760,283.12076,102448.375,101995.414,2.992889,2.410894,0.000000,12236688.0,2020-01-06,6565.323606
4,2020_22784,4.93,11.11,2020-01-06 00:00:00,2020-01-13 00:00:00,8,1.1,0.62,0.88,southeast,...,292.18143,294.35640,101801.750,101360.100,2.985026,2.405601,0.025873,2535104.0,2020-01-11,6565.323606

In [4]:
# view feature data
data.describe()

,size (km2),perimiter (km),duration,fire_line (km),fire_spread (km2/day),fire_speed (km/day),index_right,latitude,longitude,u10,...,v10,d2m,t2m,msl,sp,lai_hv,lai_lv,tp,ssr,dist
count,32082.000000,32082.000000,32082.000000,32082.000000,32082.000000,32082.00000,3.208200e+04,32082.000000,32082.000000,32082.000000,...,32082.000000,32082.000000,32082.000000,32082.000000,32082.000000,32082.000000,32082.000000,32082.000000,3.208200e+04,32082.000000
mean,19.627479,29.133438,12.941774,2.496167,1.620429,2.20623,1.410558e+06,38.488632,-103.098714,0.128195,...,0.341190,280.752792,290.498979,101587.466259,95404.544994,2.717593,1.764379,0.001590,1.680758e+07,9411.910052
std,49.696907,27.715941,5.844891,3.886487,4.010768,1.70552,6.795278e+05,8.861038,18.942586,1.832064,...,2.349705,8.882896,7.656374,614.691170,7389.700655,1.142001,0.716741,0.004740,5.577529e+06,3635.845120
min,4.070000,9.260000,1.000000,0.350000,0.170000,0.58000,5.014000e+03,19.650000,-165.850000,-9.022443,...,-10.041690,247.640150,256.153400,99178.340000,70101.730000,0.000000,0.000000,0.000000,4.577280e+05,250.207361
25%,5.360000,15.740000,8.000000,0.930000,0.450000,1.30000,8.644580e+05,33.150000,-114.850000,-1.051346,...,-1.024666,274.147685,285.338530,101231.480000,91950.432500,2.030273,1.265003,0.000000,1.331969e+07,6686.224160
50%,7.930000,20.370000,12.000000,1.470000,0.730000,1.73000,1.391799e+06,36.650000,-96.600000,0.174160,...,0.299106,280.678035,290.937680,101582.675000,97986.463000,2.593112,1.686295,0.000029,1.739407e+07,9681.550126
75%,14.150000,31.480000,17.000000,2.620000,1.410000,2.49000,1.957546e+06,42.900000,-90.600000,1.194915,...,1.707381,287.887285,296.530053,101939.154250,100956.050000,3.549260,2.393430,0.000806,2.063463e+07,12217.278808
max,806.240000,298.170000,31.000000,140.600000,134.500000,26.19000,2.923831e+06,68.650000,-74.350000,11.458554,...,10.673229,299.197050,311.581670,104212.430000,103518.164000,5.127843,3.819295,0.142104,2.985043e+07,17855.839385

In [5]:
# view feature data
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32082 entries, 0 to 32081
Data columns (total 30 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   unique_id              32082 non-null  object
 1   size (km2)             32082 non-null  float64
 2   perimiter (km)         32082 non-null  float64
 3   startdate              32082 non-null  object
 4   enddate                32082 non-null  object
 5   duration               32082 non-null  int64
 6   fire_line (km)         32082 non-null  float64
 7   fire_spread (km2/day)  32082 non-null  float64
 8   fire_speed (km/day)    32082 non-null  float64
 9   dominant_direction     32082 non-null  object
 10  geometry               32082 non-null  object
 11  burn_start             32082 non-null  object
 12  burn_end               32082 non-null  object
 13  index_right            32082 non-null  int64
 14  valid_time             32082 non-null  object
 15  latitude               32082 non-null  float64
 16  longitude              32082 non-null  float64
 17  u10                    32082 non-null  float64
 18  number                 32082 non-null  int64
 19  v10                    32082 non-null  float64
 20  d2m                    32082 non-null  float64
 21  t2m                    32082 non-null  float64
 22  msl                    32082 non-null  float64
 23  sp                     32082 non-null  float64
 24  lai_hv                 32082 non-null  float64
 25  lai_lv                 32082 non-null  float64
 26  tp                     32082 non-null  float64
 27  ssr                    32082 non-null  float64
 28  datetime               32082 non-null  object
 29  dist                   32082 non-null  float64
dtypes: float64(18), int64(3), object(9)
memory usage: 7.3+ MB

In [6]:
# extract year from startdate
data['year'] = pd.to_datetime(data['startdate'], errors='coerce').dt.year

In [7]:
# split data
train_data = data[data['year'].isin([2020, 2021, 2022])]
test_data = data[data['year'].isin([2023, 2024])]

In [8]:
# Predictors and Targets
predictors = ['u10', 'v10', 'd2m', 't2m', 'msl', 'sp', 'lai_hv', 'lai_lv', 'tp', 'ssr']
target1 = 'size (km2)'
target2 = 'fire_spread (km2/day)'
target3 = 'duration'

In [11]:
# Split features and targets
X_train = train_data[predictors]
X_test = test_data[predictors]
y1_train = train_data[target1]
y2_train = train_data[target2]
y3_train = train_data[target3]
y1_test = test_data[target1]
y2_test = test_data[target2]
y3_test = test_data[target3]

In [12]:
# BASELINE PREDICTIONS: mean of training set
baseline1 = np.full_like(y1_test, fill_value=y1_train.mean(), dtype=np.float64)
baseline2 = np.full_like(y2_test, fill_value=y2_train.mean(), dtype=np.float64)
baseline3 = np.full_like(y3_test, fill_value=y3_train.mean(), dtype=np.float64)

In [18]:
# Compute Baseline Errors (MSE & RMSE)
def compute_baseline_metrics(y_true, y_pred, target_name):
    mse = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    print(f"\nBaseline metrics for predicting {target_name}:")
    print(f"Mean training set target value: {y_pred[0]:.4f}")
    print(f"Baseline MSE: {mse:.4f}")
    print(f"Baseline RMSE: {rmse:.4f}")

# Evaluate baseline performance
compute_baseline_metrics(y1_test, baseline1, target1)
compute_baseline_metrics(y2_test, baseline2, target2)
compute_baseline_metrics(y3_test, baseline3, target3)

Baseline metrics for predicting size (km2):
Mean training set target value: 21.2216
Baseline MSE: 1114.3064
Baseline RMSE: 33.3812

Baseline metrics for predicting fire_spread (km2/day):
Mean training set target value: 1.6272
Baseline MSE: 41.9301
Baseline RMSE: 6.4753

Baseline metrics for predicting duration:
Mean training set target value: 13.2761
Baseline MSE: 29.8665
Baseline RMSE: 5.4650